global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer"
    static_configs:
      - targets: ["orderer.example.com:9443"]
  - job_name: "peer0_farmer"
    static_configs:
      - targets: ["peer0.farmer.example.com:9444"]
  - job_name: "peer0_logistics"
    static_configs:
      - targets: ["peer0.logistics.example.com:9445"]
  - job_name: "peer0_warehouse"
    static_configs:
      - targets: ["peer0.warehouse.example.com:9446"]
  - job_name: "peer0_buyer"
    static_configs:
      - targets: ["peer0.buyer.example.com:9447"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
